version: '2'
services:
  db:
    image: mdillon/postgis:latest
    volumes:
      - './.data/db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: farmos
      POSTGRES_PASSWORD: farmos

  www:
    depends_on:
      - db
#    image: farmos/farmos:7.x-1.0-beta15
    image: farmos/farmos:7.x-1.x
    volumes:
      - './.data/www:/var/www/html'
    links:
      - db
    ports:
      - '80:80'
    environment:
      FARMOS_DEV: 'true'
